name: 'Notify Kyanite to Deploy'
description: 'The package posts to the Kyanite webhook to notify of a push.'
author: 'MainframeDev'

inputs:
  secret_key:
    description: 'The key which will be used for the X-Kyanite-Deployment-Security header.'
    required: true

  host:
    description: 'The Kyanite deploy route root.'
    required: true
    default: 'https://server.stumblepriv.xyz/kyanite/api/deploy'

  slug:
    description: 'Slug of the workflow we want to execute. Defined in Slugs.yaml of the destination host.'
    required: true

runs:
  using: node20
  main: dist/index.js