name: 'Notify Kyanite to Deploy'
description: 'The package posts to the Kyanite webhook to notify of a push.'
author: 'MainframeDev'

inputs:
  secret_key:
    description: 'The key which will be used for the X-Kyanite-Deployment-Security header.'
    required: true

  host:
    description: 'The StumbleServer deploy route root.'
    required: true
    default: 'https://server.stumblepriv.xyz/ci/api/upload'

  branch:
    description: 'Branch (short ref)'
    required: true

  commit:
    description: 'Commit (long)'
    required: true

  dll_path:
    description: 'Path to built DLL file'
    required: true

runs:
  using: node20
  main: dist/index.js